### ISSUE TITLE
Check Basilisk buildablity on Target Operating Systems

### ISSUE THREAD

**Issue by mattatobin** [MoonchildProductions/Basilisk#1]
@trav90 @athenian200 @adeshkp @JustOff 

Blocks MoonchildProductions/UXP#969

**Comment by JustOff** [comment]
✔ win32 build was done w/o any issues

**Comment by adeshkp** [comment]
Mac: builds fine, runs ok.

**Comment by athenian200** [comment]
Solaris/illumos doesn't actually have support for WebRTC implemented in the platform, but Basilisk as an application builds fine if you disable that. No change from before it was comm-ized, that's the status quo.

**Comment by trav90** [comment]
All good here on Linux. :+1:

**Comment by mattatobin** [comment]
Thank you all for your testing and your adaptability during this transition. There will be some new documentation written up that will help you further on how to proceed most effectively under the new setup.
