### ISSUE TITLE
--enable-alsa not present in buildconfig / basilisk / linux

### ISSUE THREAD

**Issue by mrkapqa** [MoonchildProductions/Basilisk#11]
Hello ,

is it possible for user to enable alsa manually or is this already accomplished?

downloaded the latest tar.gz from your homepage and it seems very promising;

however, it seems alsa is not active?

about:buildconfig is giving no indication

--enable-application=basilisk --with-external-source-dir=/home/PM4Linux/REPO/Basilisk --enable-update-channel=release --disable-debug-symbols --enable-jemalloc --enable-default-toolkit=cairo-gtk3 --enable-av1 MAKE=/usr/bin/gmake --enable-eme --enable-gamepad --enable-official-branding --enable-official-vendor '--enable-optimize=-O2 -msse -mfpmath=sse' --enable-strip --disable-tests --enable-updater --enable-webrtc --with-pthreads --x-libraries=/usr/lib64

**Comment by mattatobin** [comment]
Please don't close issues yourself.

**Comment by mrkapqa** [comment]
thanks,

the alsa seems active.
my issue has been caused by the .asoundrc that i created to cirumvent alsa's preference for the internal hdmi port as primary soundcard.
with the .asoundrc i could activate the internal soundcard as primary card, but the browser playback would not respond and block playbacck for some reason (mpv or other players would playback).
after deleting .asoundrc and creating another solution for selecting the soundcard as shown here in the wiki 
https://wiki.archlinux.org/index.php/Advanced_Linux_Sound_Architecture#Set_the_default_sound_card
(bit tricky)
the playback on the browsers became operational (and also on basilisk that by default should be alsa-enabled as stated in their documentary).
