### ISSUE TITLE
discord voicechat no longer working

### ISSUE THREAD

**Issue by XP-Fan** [MoonchildProductions/Basilisk#15]
Hey guys, I do know this is not a discord-support but rather about the Basilisk webbrowser. However, this issue seems to be particularly specific to discord (http://discordapp.com) in combination with basilisk. Since about 2 days, the voicechat-functionality is broken, which to me definitely means that there must be some fancy modern API basilisk does not support. I suppose this shall be fixed asap, as it is probably not discord only, they might've been the ones to start, but more pages might decide to use that API/whatever missing thing in the future, so I really really hope Basilisk'll catch up soon... Anyway by this chance I wanna thank you guys for maintaining this as it's the most awesome browser in the world...

**Comment by wolfbeast** [comment]
Duplicated in UXP by reporter. Please don't - we'll move it if necessary.
