### ISSUE TITLE
Could you provide build instruction on your website?

### ISSUE THREAD

**Issue by hoper-a11y** [MoonchildProductions/Basilisk#20]
I want to build Basilisk from source. But so far I didn't see anything about it apart from a guide for PaleMoon on the developer site: https://developer.palemoon.org/build/linux/

What is the recommended .mozconfig for Basilisk? Thanks.

**Comment by mattatobin** [comment]
I believe there are no plans for that.

**Comment by hoper-a11y** [comment]
> I believe there are no plans for that.

So what is the recommended .mozconfig? The config you used to build your release version of Basilisk. Could I just adapt the .mozconfig sample from the guide for PaleMoon? Thanks.

**Comment by hoper-a11y** [comment]
I used the same .mozconfig as of PaleMoon and only changed the application name to basilisk. It worked. The basilisk version I build worked fine so far, but I don't know how it's different from the official build. I'm on Linux, SparkyLinux Rolling.
