### ISSUE TITLE
Legacy Tab Tree and Tree Style Tabs are not working

### ISSUE THREAD

**Issue by viking2** [MoonchildProductions/Basilisk#24]
I have tried two different Legacy Tab Trees: Tab Tree by  Sergey Zennsov and Tree Style Tabs by "Piro". Neither works with Basilisk.

**Comment by mattatobin** [comment]
And what do you expect us to do about it?

**Comment by viking2** [comment]
I thought that one of the main purposes of Basilisk was to support Legacy extensions while keeping security updates? 

I am trying to understand why it works on Firefox (and Waterfox) but not on Basilisk?

**Comment by mattatobin** [comment]
Extensions support Applications not the other way around.
