### ISSUE TITLE
How to unlock multi process 

### ISSUE THREAD

**Issue by andika207** [MoonchildProductions/Basilisk#25]
I want to know if there is a way to unlock the multi process function on Basilisk.
with heavy load sites such as facebook it's almost unusable however Firefox or Chromium are really smooth.

**Comment by mattatobin** [comment]
You can't this is not a feature in any UXP application regardless of any remaining code for it.

Do some basic research first next time and use the forum for questions.

**Comment by andika207** [comment]
@mattatobin isn't the Serpent browser a fork of the Basilisk ?
 it has the multi process mode disabled by default but it's 100% functional once you turn it on.

**Comment by mattatobin** [comment]
Please don't bother us with corruped old and insecure xp builds.
