### ISSUE TITLE
mattatobin don't get me wrong

### ISSUE THREAD

**Issue by andika207** [MoonchildProductions/Basilisk#26]
Please don't bother us with corruped old and insecure xp builds.

_Originally posted by @mattatobin in https://github.com/MoonchildProductions/Basilisk/issues/25#issuecomment-663821909_

No I don't want to bother you. 
I just want you to tell me why you don't want to unlock the multi process mode for Basilisk.
if it works for XP it should be fine for W7 as well.
I told you that the Basilisk under W7 is barely usable due to the lack of multi processes.
Maybe your Basilisk browser is totally different form mine so it performs much better....

**Comment by mattatobin** [comment]
Please stop opening irrelevant issues.
