### ISSUE TITLE
Certificate Manager?

### ISSUE THREAD

**Issue by fugo** [MoonchildProductions/Basilisk#28]
2020.06.15 on Linux  
Where can I find the stored certificates to export some?

NSS - S/Mime certificates

**Comment by mattatobin** [comment]
`about:preferences` > Advanced > Security

**Comment by fugo** [comment]
I found Preferences ->Advanced before
But in this version it's a dead link
If I use `about:preferences#advanced`it jumps to general.

**Comment by wolfbeast** [comment]
about:preferences#advanced works for me.
