### ISSUE TITLE
Error Pages claim to be Firefox

### ISSUE THREAD

**Issue by Nigaikaze** [MoonchildProductions/Basilisk#4]
The first line of text on the "Server not found" page says "_Firefox_ can’t find the server at suchandsuch.com" instead of "_Basilisk_ can’t find the server..."  Pic attached.

![Server Not Found](https://user-images.githubusercontent.com/60270406/73093661-9d218600-3ea4-11ea-84ee-73e43a3f39f7.jpg)

**Comment by mattatobin** [comment]
Basilisk has been out for two years.. Wonder why all these mentions of Firefox strings are just being noticed now?

**Comment by mattatobin** [comment]
This has to do with appstrings.properties for some reason Firefox is hardcoded in these strings. I will change them to Basilisk but a branding agnostic solution is REALLY needed and not only for Basilisk.
