### ISSUE TITLE
Basilisk Branding/Redistribution

### ISSUE THREAD

**Issue by djames1** [MoonchildProductions/Basilisk#6]
I am familiar with the Pale Moon branding information located [here](https://www.palemoon.org/branding.shtml). However I am not able to find a similar page related to the Basilisk branding. What are users allowed to do/not do with the Basilisk branding?

Also, I am not able to find a page for Basilisk equivalent to the Pale Moon redistribution info page as seen [here](https://www.palemoon.org/redist.shtml). What are our rights when it comes to redistribution of Basilisk-related material, be it precompiled binaries or our own custom binaries?

**Comment by mattatobin** [comment]
You are not allowed to redistribute anything but verified unaltered binaries without express permission from Moonchild.

**Comment by djames1** [comment]
@mattatobin I am investigating making a Gentoo package for Basilisk similar to the Gentoo Pale Moon package. I will move the discussion to the forums.

Thank you!

**Comment by mattatobin** [comment]
You already

**Comment by EchedeyLR** [comment]
Can I ask for the link to the forum?

**Comment by djames1** [comment]
@EchedeyLR I never created a thread on the forums. I just created a Gentoo package with the official branding disabled instead.

**Comment by EchedeyLR** [comment]
Thank you for the reply ^^
