### ISSUE TITLE
Source code of latest release v2020.03.04 ?

### ISSUE THREAD

**Issue by Vangelis66** [MoonchildProductions/Basilisk#8]
Greetings 😃 ; first, I am fully aware that non-development questions should be best forwarded to the official forums, _however_ I feel that my query below is more closely linked to the GitHub repo(s) here than being forum material... 😉 ; of course, you are free to say otherwise if I am at fault, in which case I apologise profusely and in advance... So here it goes: 

Up to and including the previous Basilisk release **2020.02.18**, it was my understanding that the `UXP release` branch was merged into the `UXP Basilisk-release` branch and then a Basilisk release was cut based on that code snapshot; that release would then appear as a **release** and/or **tag** under `https://github.com/MoonchildProductions/UXP/(releases|tags)`; it is hence fully transparent that the [previous release](https://github.com/MoonchildProductions/UXP/releases/tag/v2020.02.18) was built on https://github.com/MoonchildProductions/UXP/commit/39a3d75915ae6a150c4a2402210afea59bae0b15

Fast forward to the latest release **2020.03.04** and from its [Release Notes](https://www.basilisk-browser.org/releasenotes.shtml) I quote: 

> New modular setup for building: **Basilisk has been split off from the UXP platform repository** 

If I interpret the above correctly, there will be no more **Basilisk** releases/tags appearing inside the UXP repo, but will/should they appear **elsewhere**? 

> and will be maintained as its own application with UXP as a platform module.

Am I correct to assume that **this** repo is the one Basilisk development _as an application_ has shifted to? Going by the **date format** (03.04) in the latest release _version_, was the latest release built on 3b5e5c91dfeb4ca4a1f642457b2916a995ca44a6 ? In any case, the source code of the **latest build** isn't now _easily transparent_ and the link in the [**official download page**](https://www.basilisk-browser.org/download.shtml), 

> Source code
> 
> You can find the source code of our releases and tagged commits on [GitHub](https://github.com/MoonchildProductions/UXP/releases). 

... is a _catch 22_, as it directs to the **UXP** repo (where no trace of a Bk **2020.03.04** source code is to be found... 😞 ).

Thank you hugely for any insight, as ever your unwaning efforts in swimming against the tide that is Google and their monopoly is highly appreciated 🥇

**Comment by wolfbeast** [comment]
https://github.com/MoonchildProductions/Basilisk/releases/tag/v2020.03.04

**Comment by Vangelis66** [comment]
Thanks for your swift actions; all good now! 👍 Please take the best of care... 😉
